"""is_google_user

Revision ID: 20e884c03fd4
Revises: d15aecd42416
Create Date: 2023-08-22 22:09:20.429948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20e884c03fd4'
down_revision = 'd15aecd42416'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_google_user', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_google_user')
    # ### end Alembic commands ###
