"""email_and_users_separarte_unique_index

Revision ID: 51e8d44bdb0a
Revises: 1871d44e2f6b
Create Date: 2023-08-22 17:58:56.678077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51e8d44bdb0a'
down_revision = '1871d44e2f6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_unique_non_deleted_user_names', table_name='users')
    op.drop_index('ix_unique_non_deleted_users_by_email', table_name='users')
    op.create_unique_constraint('unique_user_emails', 'users', ['email'])
    op.create_unique_constraint('unique_user_names', 'users', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_names', 'users', type_='unique')
    op.drop_constraint('unique_user_emails', 'users', type_='unique')
    op.create_index('ix_unique_non_deleted_users_by_email', 'users', ['email', 'is_deleted'], unique=False)
    op.create_index('ix_unique_non_deleted_user_names', 'users', ['name', 'is_deleted'], unique=False)
    # ### end Alembic commands ###
