"""drop_unique_user_name_index

Revision ID: ae53f60cf5c7
Revises: b6beb392c0cb
Create Date: 2023-08-20 22:48:17.664426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae53f60cf5c7'
down_revision = 'b6beb392c0cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_names', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_user_names', 'users', ['name'])
    # ### end Alembic commands ###
