"""remove_user_name_unique_index

Revision ID: d15aecd42416
Revises: 51e8d44bdb0a
Create Date: 2023-08-22 22:00:12.613053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd15aecd42416'
down_revision = '51e8d44bdb0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_names', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_user_names', 'users', ['name'])
    # ### end Alembic commands ###
